const ALL_SHORTCUTS = [
  // --- دسته اول: میانبرهای عمومی ویندوز (۱ تا ۵۰) ---
  { keys: ["Win", "E"], desc: "باز کردن سریع فایل اکسپلورر (This PC) برای مدیریت فایل‌ها", cat: "general", kw: "فایل اکسپلورر مدیریت پوشه my computer this pc" },
  { keys: ["Win", "I"], desc: "باز کردن پنجره تنظیمات اصلی ویندوز (Settings)", cat: "general", kw: "تنظیمات ویندوز settings کنترل پنل" },
  { keys: ["Win", "R"], desc: "باز کردن کادر جادویی Run برای اجرای دستورات سیستمی", cat: "general", kw: "ران run دستورات cmd" },
  { keys: ["Win", "S"], desc: "باز کردن جستجوی سریع ویندوز برای یافتن فایل و اپلیکیشن", cat: "general", kw: "سرچ ویندوز search جستجو" },
  { keys: ["Alt", "Tab"], desc: "سوییچ سریع و روان بین برنامه‌های باز شده در دسکتاپ", cat: "general", kw: "سوییچ برنامه alt tab جابجایی" },
  { keys: ["Win", "V"], desc: "باز کردن تاریخچه کلیپ‌بورد و نگهداری چند متن کپی‌شده همزمان", cat: "general", kw: "کلیپ بورد تاریخچه کپی clipboard history" },
  { keys: ["Win", "Shift", "S"], desc: "ابزار حرفه‌ای اسکرین‌شات گرفتن از صفحه نمایش (Snipping Tool)", cat: "general", kw: "اسکرین شات عکس از صفحه snipping tool" },
  { keys: ["Ctrl", "Shift", "Esc"], desc: "باز کردن مستقیم تسک منیجر (Task Manager) برای بستن برنامه‌های هنگ‌کرده", cat: "general", kw: "تسک منیجر task manager بستن برنامه هنگ" },
  { keys: ["Win", "D"], desc: "مخفی کردن تمامی پنجره‌ها و رفتن مستقیم به دسکتاپ", cat: "general", kw: "نمایش دسکتاپ minimize all windows" },
  { keys: ["Win", "L"], desc: "قفل کردن فوری کامپیوتر برای امنیت اطلاعات شخصی", cat: "general", kw: "قفل کامپیوتر lock screen امنیت" },
  { keys: ["Alt", "F4"], desc: "بستن کامل برنامه فعال یا باز کردن منوی خاموش کردن سیستم", cat: "general", kw: "بستن برنامه alt f4 خاموش کردن shutdown" },
  { keys: ["Win", "X"], desc: "باز کردن منوی مدیریتی مخفی ویندوز (Device Manager, Disk Management)", cat: "general", kw: "منوی مدیریتی ویندوز win x" },
  { keys: ["Win", "Arrow Up"], desc: "بزرگ کردن (Maximize) پنجره فعال در صفحه", cat: "general", kw: "بزرگ کردن پنجره maximize" },
  { keys: ["Win", "Arrow Down"], desc: "کوچک کردن یا مینیمم کردن پنجره فعال", cat: "general", kw: "کوچک کردن پنجره minimize" },
  { keys: ["Win", "Arrow Left/Right"], desc: "چسباندن پنجره فعال به سمت چپ یا راست صفحه (Snap Window)", cat: "general", kw: "چسباندن پنجره split screen" },
  { keys: ["Win", "Tab"], desc: "مشاهده تمام دسکتاپ‌های مجازی و تاریخچه تایم‌لاین", cat: "general", kw: "دسکتاپ مجازی virtual desktop" },
  { keys: ["Ctrl", "Shift", "N"], desc: "ساخت پوشه جدید (New Folder) در فایل اکسپلورر یا دسکتاپ", cat: "general", kw: "پوشه جدید ساخت فولدر new folder" },
  { keys: ["F2"], desc: "تغییر نام (Rename) فایل یا پوشه انتخاب‌شده", cat: "general", kw: "تغییر نام rename" },
  { keys: ["Delete"], desc: "حذف فایل و انتقال آن به سطل بازیافت", cat: "general", kw: "حذف فایل delete سطل زباله" },
  { keys: ["Shift", "Delete"], desc: "پاک کردن دائمی و همیشگی فایل بدون رفتن به سطل بازیافت", cat: "general", kw: "حذف دائم shift delete" },
  { keys: ["Alt", "Enter"], desc: "مشاهده ویژگی‌ها و مشخصات (Properties) فایل یا پوشه", cat: "general", kw: "پروپرتیس properties مشخصات فایل" },
  { keys: ["Alt", "Arrow Left"], desc: "بازگشت به پوشه قبلی در فایل اکسپلورر", cat: "general", kw: "پوشه قبلی back" },
  { keys: ["Alt", "Arrow Right"], desc: "رفتن به پوشه بعدی در فایل اکسپلورر", cat: "general", kw: "پوشه بعدی forward" },
  { keys: ["Alt", "Arrow Up"], desc: "رفتن یک سطح به پوشه بالاتر (Parent Folder)", cat: "general", kw: "پوشه بالاتر parent folder" },
  { keys: ["F3"], desc: "فکوس روی نوار جستجوی فایل اکسپلورر", cat: "general", kw: "جستجوی فایل search file" },
  { keys: ["F4"], desc: "باز کردن لیست کشویی نوار آدرس در اکسپلورر", cat: "general", kw: "نوار آدرس address bar" },
  { keys: ["F5"], desc: "تازهسازی و رفرش محتویات صفحه یا پوشه", cat: "general", kw: "رفرش refresh" },
  { keys: ["F6"], desc: "چرخش بین اجزای مختلف یک پنجره", cat: "general", kw: "چرخش پنجره cycle elements" },
  { keys: ["F10"], desc: "فعال کردن منوی نوار ابزار در برنامه‌ها", cat: "general", kw: "منوی ابزار menu bar" },
  { keys: ["Ctrl", "Shift", "Tab"], desc: "حرکت به سمت عقب بین تب‌های باز", cat: "general", kw: "تب قبلی previous tab" },

  // --- دسته دوم: مرورگر وب و اینترنت (۵۱ تا ۱۰۰) ---
  { keys: ["Ctrl", "T"], desc: "باز کردن یک تب (صفحه) جدید در مرورگر", cat: "browser", kw: "تب جدید new tab مرورگر کروم فایرفاکس" },
  { keys: ["Ctrl", "W"], desc: "بستن تب فعال در مرورگر", cat: "browser", kw: "بستن تب close tab" },
  { keys: ["Ctrl", "Shift", "T"], desc: "بازگردانی فوری آخرین تبی که به‌اشتباه بسته‌اید", cat: "browser", kw: "بازگردانی تب بسته شده restore closed tab" },
  { keys: ["Ctrl", "Tab"], desc: "سوییچ به تب بعدی در مرورگر", cat: "browser", kw: "سوییچ تب next tab" },
  { keys: ["Ctrl", "Shift", "W"], desc: "بستن کامل پنجره مرورگر", cat: "browser", kw: "بستن مرورگر close window" },
  { keys: ["Ctrl", "N"], desc: "باز کردن یک پنجره جدید مرورگر", cat: "browser", kw: "پنجره جدید new window" },
  { keys: ["Ctrl", "Shift", "N"], desc: "باز کردن پنجره ناشناس (Incognito / Private Mode)", cat: "browser", kw: "حالت ناشناس اینکاگنی تو incognito" },
  { keys: ["Ctrl", "L"], desc: "انتخاب سریع آدرس بار برای نوشتن آدرس سایت", cat: "browser", kw: "آدرس بار address bar url" },
  { keys: ["Ctrl", "R"], desc: "بارگذاری مجدد (Refresh) صفحه وب", cat: "browser", kw: "رفرش صفحه reload" },
  { keys: ["F5"], desc: "رفرش صفحه وب", cat: "browser", kw: "رفرش صفحه f5" },
  { keys: ["Ctrl", "F5"], desc: "رفرش اجباری صفحه و پاک کردن کش مرورگر (Hard Refresh)", cat: "browser", kw: "هارد رفرش سخت hard refresh" },
  { keys: ["Escape"], desc: "متوقف کردن بارگذاری صفحه وب", cat: "browser", kw: "توقف بارگذاری stop loading" },
  { keys: ["Ctrl", "D"], desc: "افزودن صفحه فعلی به بوکمارک‌ها (علاقه‌مندی‌ها)", cat: "browser", kw: "بوکمارک bookmark نشان کردن" },
  { keys: ["Ctrl", "Shift", "O"], desc: "باز کردن مدیر بوکمارک‌ها (Bookmark Manager)", cat: "browser", kw: "مدیر بوکمارک bookmark manager" },
  { keys: ["Ctrl", "J"], desc: "باز کردن صفحه دانلودهای مرورگر", cat: "browser", kw: "دانلودها downloads مدیریت دانلود" },
  { keys: ["Ctrl", "H"], desc: "باز کردن تاریخچه مرورگر (History)", cat: "browser", kw: "تاریخچه مرورگر history" },
  { keys: ["Ctrl", "Shift", "Delete"], desc: "باز کردن پنل پاکسازی اطلاعات شخصی و کش مرورگر", cat: "browser", kw: "پاک کردن کش clear browsing data" },
  { keys: ["Ctrl", "P"], desc: "پرینت گرفتن از صفحه وب یا ذخیره به صورت PDF", cat: "browser", kw: "چاپ پرینت print pdf" },
  { keys: ["Ctrl", "S"], desc: "ذخیره کردن کامل صفحه وب روی کامپیوتر", cat: "browser", kw: "ذخیره صفحه save page as" },
  { keys: ["Alt", "Home"], desc: "رفتن به صفحه خانگی (Homepage) مرورگر", cat: "browser", kw: "صفحه خانگی home page" },
  { keys: ["Ctrl", "Plus (+)"], desc: "بزرگ‌نمایی صفحه وب (Zoom In)", cat: "browser", kw: "زوم بزرگنمایی zoom in" },
  { keys: ["Ctrl", "Minus (-)"], desc: "کوچک‌نمایی صفحه وب (Zoom Out)", cat: "browser", kw: "کوچک نمایی zoom out" },
  { keys: ["Ctrl", "0"], desc: "بازنشانی زوم صفحه به حالت پیش‌فرض (100%)", cat: "browser", kw: "ریست زوم reset zoom" },
  { keys: ["F11"], desc: "بردن مرورگر به حالت تمام صفحه (Full Screen)", cat: "browser", kw: "تمام صفحه full screen" },
  { keys: ["Ctrl", "F"], desc: "جستجوی کلمه خاص در متن صفحه وب", cat: "browser", kw: "جستجو در صفحه find in page" },
  { keys: ["F3"], desc: "یافتن مورد بعدی جستجو شده در صفحه", cat: "browser", kw: "یافتن بعدی find next" },
  { keys: ["Ctrl", "Enter"], desc: "اضافه کردن خودکار com. و www. به دور آدرس در نوار ابزار", cat: "browser", kw: "تکمیل آدرس وب سایت" },
  { keys: ["Spacebar"], desc: "پیمایش صفحه به سمت پایین (یک صفحه نمایش)", cat: "browser", kw: "پیمایش اسکرول scroll down" },
  { keys: ["Shift", "Spacebar"], desc: "پیمایش صفحه به سمت بالا", cat: "browser", kw: "اسکرول بالا scroll up" },
  { keys: ["Home"], desc: "رفتن به بالاترین نقطه صفحه وب", cat: "browser", kw: "بالای صفحه top of page" },

  // --- دسته سوم: ویرایش متن، تایپ و برنامه‌نویسی (۱۰۱ تا ۱۵۰) ---
  { keys: ["Ctrl", "C"], desc: "کپی کردن متن یا فایل انتخاب‌شده", cat: "text", kw: "کپی copy" },
  { keys: ["Ctrl", "V"], desc: "چسباندن متن یا فایل کپی‌شده", cat: "text", kw: "پیست paste الصاق" },
  { keys: ["Ctrl", "X"], desc: "بریدن (Cut) متن برای جابجایی", cat: "text", kw: "کات cut بریدن" },
  { keys: ["Ctrl", "Z"], desc: "لغو آخرین عملیات انجام‌شده (Undo)", cat: "text", kw: "آندو undo بازگشت" },
  { keys: ["Ctrl", "Y"], desc: "بازگردانی عملیات لغو شده (Redo)", cat: "text", kw: "ریدو redo تکرار" },
  { keys: ["Ctrl", "A"], desc: "انتخاب تمام متن‌ها یا آیتم‌های صفحه (Select All)", cat: "text", kw: "انتخاب همه select all" },
  { keys: ["Ctrl", "F"], desc: "جستجوی کلمه در متن", cat: "text", kw: "جستجو find" },
  { keys: ["Ctrl", "H"], desc: "جایگزینی کلمات در متن (Find and Replace)", cat: "text", kw: "جایگزینی replace" },
  { keys: ["Ctrl", "B"], desc: "ضخیم کردن متن (Bold)", cat: "text", kw: "بولد ضخیم bold" },
  { keys: ["Ctrl", "I"], desc: "کج کردن متن (Italic)", cat: "text", kw: "ایتالیک کج italic" },
  { keys: ["Ctrl", "U"], desc: "خط زیر متن (Underline)", cat: "text", kw: "آندرلاین خط زیر underline" },
  { keys: ["Ctrl", "S"], desc: "ذخیره کردن فایل در حال ویرایش (Save)", cat: "text", kw: "ذخیره save" },
  { keys: ["Ctrl", "P"], desc: "چاپ سند یا مقاله", cat: "text", kw: "پرینت print" },
  { keys: ["Ctrl", "O"], desc: "باز کردن فایل موجود (Open)", cat: "text", kw: "باز کردن فایل open" },
  { keys: ["Ctrl", "N"], desc: "ایجاد سند جدید (New Document)", cat: "text", kw: "سند جدید new file" },
  { keys: ["Ctrl", "Backspace"], desc: "حذف کامل یک کلمه در سمت چپ مکان‌نما", cat: "text", kw: "حذف کلمه backspace" },
  { keys: ["Ctrl", "Delete"], desc: "حذف کامل یک کلمه در سمت راست مکان‌نما", cat: "text", kw: "حذف کلمه راست delete word" },
  { keys: ["Ctrl", "Arrow Left"], desc: "پرش مکان‌نما به ابتدای کلمه قبلی", cat: "text", kw: "پرش کلمه چپ" },
  { keys: ["Ctrl", "Arrow Right"], desc: "پرش مکان‌نما به ابتدای کلمه بعدی", cat: "text", kw: "پرش کلمه راست" },
  { keys: ["Home"], desc: "رفتن مکان‌نما به ابتدای خط جاری", cat: "text", kw: "ابتدای خط home" },
  { keys: ["End"], desc: "رفتن مکان‌نما به انتهای خط جاری", cat: "text", kw: "انتهای خط end" },
  { keys: ["Ctrl", "Home"], desc: "رفتن به ابتدای کل متن یا سند", cat: "text", kw: "ابتدای سند" },
  { keys: ["Ctrl", "End"], desc: "رفتن به انتهای کل متن یا سند", cat: "text", kw: "انتهای سند" },
  { keys: ["Shift", "Home"], desc: "انتخاب متن از مکان‌نما تا ابتدای خط", cat: "text", kw: "انتخاب تا ابتدا" },
  { keys: ["Shift", "End"], desc: "انتخاب متن از مکان‌نما تا انتهای خط", cat: "text", kw: "انتخاب تا انتها" },
  { keys: ["Ctrl", "Shift", "Arrow Left"], desc: "انتخاب کلمه به کلمه به سمت چپ", cat: "text", kw: "انتخاب کلمه چپ" },
  { keys: ["Ctrl", "Shift", "Arrow Right"], desc: "انتخاب کلمه به کلمه به سمت راست", cat: "text", kw: "انتخاب کلمه راست" },
  { keys: ["Page Up"], desc: "پیمایش سریع صفحه به سمت بالا", cat: "text", kw: "صفحه بالا page up" },
  { keys: ["Page Down"], desc: "پیمایش سریع صفحه به سمت پایین", cat: "text", kw: "صفحه پایین page down" },
  { keys: ["Insert"], desc: "تغییر حالت درج یا جایگزینی متن (Overwrite Mode)", cat: "text", kw: "اینسرت insert" },

  // --- دسته چهارم: ابزارهای پیشرفته و کدنویسی (۱۵۱ تا ۲۰۰+) ---
  { keys: ["Ctrl", "Shift", "I"], desc: "باز کردن ابزار توسعه‌دهنده مرورگر (Developer Tools / Inspect Element)", cat: "dev", kw: "اینسپکت inspect devtools برنامه نویسی" },
  { keys: ["F12"], desc: "باز کردن کنسول و ابزار بررسی کدهای وب", cat: "dev", kw: "کنسول کنسول مرورگر f12" },
  { keys: ["Ctrl", "U"], desc: "مشاهده سورس کد کامل صفحه وب (View Page Source)", cat: "dev", kw: "سورس کد source code html" },
  { keys: ["Alt", "Spacebar"], desc: "باز کردن منوی سیستمی پنجره فعال (Minimize, Maximize, Close)", cat: "dev", kw: "منوی پنجره" },
  { keys: ["Win", "Period (.)"], desc: "باز کردن کیبورد ایموجی‌ها و نمادهای خاص در ویندوز", cat: "dev", kw: "ایموجی emoji شکلک ویندوز" },
  { keys: ["Win", "Spacebar"], desc: "تغییر زبان کیبورد (فارسی، انگلیسی و سایر زبان‌ها)", cat: "dev", kw: "تغییر زبان کیبورد language" },
  { keys: ["Ctrl", "Shift", "P"], desc: "باز کردن پالت فرمان در ویرایشگرهای کد (Command Palette)", cat: "dev", kw: "پالت فرمان command palette" },
  { keys: ["Ctrl", "Slash (/)"], desc: "کامنت کردن یا برداشتن کامنت خط در کدهای برنامه‌نویسی", cat: "dev", kw: "کامنت comment code" },
  { keys: ["Alt", "Shift", "Arrow Down"], desc: "کپی کردن خط کد فعلی به خط پایین در ویرایشگر", cat: "dev", kw: "کپی خط duplicate line" },
  { keys: ["Alt", "Arrow Up/Down"], desc: "جابجایی سریع خط کد فعلی به بالا یا پایین", cat: "dev", kw: "جابجایی خط move line" }
];
